### PR TITLE
Feature: tags

### PR DESCRIPTION
**Pull request by JJ-8**
Related to https://github.com/TFNS/CTFNote/issues/90 and https://github.com/TFNS/CTFNote/issues/140

### CODE REVIEW

**Comment by peace-maker** [comment]
Are you planning on merging this upstream? 👀

**Comment by JJ-8** [comment]
@peace-maker, currently that is not possible due to the order of the migrations...

**Comment by peace-maker** [comment]
If it's just the order, couldn't you rebase in a new branch against upstream main? ❤️

**Comment by JJ-8** [comment]
@peace-maker
No, because this feature is already used by me and others and therefore this migration is already applied to their databases. If I now change the order and merge in upstream, it is not possible anymore to switch back to upstream since the api will refuse to start due to the incorrect order of migrations. Therefore the migrations have to be merged strictly in the correct order. You can expect that it will take a very long time before the PR will be created and merged. However, feel free to use my fork in the mean time if you really want to use this feature.

**Comment by peace-maker** [comment]
Aw, that's bad news. I don't think merge problems with a few instances running your fork are worth it to keep useful features from the upstream project. Couldn't you merge the commits into your fork after it was added upstream and one-time-fix your deployment? Yes, it's more work for you once, but the whole CTF community would largely benefit and this sounds like a huge stall for any collaborative development of CTFNote if everyone would want their migrations to be done in a certain order. 😢 I don't think me switching to your fork is a good solution either, since it just shifts the problem.

I know it's all in your free time and your decision to upstream the work you've done, but I just feel it would be sad to keep your work in a fork. The discord bot looks great too 👍

**Comment by JJ-8** [comment]
As a reminder for myself: in order to correctly upstream this PR, https://github.com/JJ-8/CTFNote/pull/52 should be cherry picked too.

**Pull request merged**
